### ISSUE TITLE
BLEU with UVR-NMT

### ISSUE THREAD

**Issue by Hannibal046** [ictnlp/PLUVR#5]
Hi, thanks for the great work. I am wondering why there is an obvious gap between the BLEU score in your paper and that in `UVR-NMT`, since you all conduct experiments on Multi30k dataset. Do I miss something here ?
## Your paper
<img width="1123" alt="2203 10299 pdf 2022-06-30 16-46-39" src="https://user-images.githubusercontent.com/38466901/176634678-ea1e20fd-980c-4eed-b77e-e745c8345123.png">

## UVR-NMT paper
<img width="970" alt="pdf?id=Byl8hhNYPS 2022-06-30 16-48-18" src="https://user-images.githubusercontent.com/38466901/176634709-c1b81300-8e1f-43d3-b335-5ab17b87ee7d.png">

**Comment by Poeroz** [comment]
Hi, thanks for your interest in our paper! We implement their method with a stronger baseline (attention heads=4, dropout=0.3), while they conducted experiments with Transformer-base, so our BLEU scores are higher than theirs.
