### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'region_embedding.npy

### ISSUE THREAD

**Issue by lxianl455** [ictnlp/PLUVR#6]
What should I do?

**Comment by ZengLei-dev** [comment]
I have the same problem when I run the train.py in the vae floder, How can I solve it？
![1678959332389](https://user-images.githubusercontent.com/53669083/225575663-ef62403b-3c32-497f-88a4-6499e09656dd.png)

**Comment by ZhenLEI96** [comment]
I have the same problem。

**Comment by ZhenLEI96** [comment]
> I have the same problem。

I think this file might be the result of running the extract_feature.py

**Comment by Poeroz** [comment]
Hi all,

Sorry for the late reply. We have updated the download url of `region_embedding.npy` in the README.md. Please download it via Baidu netdisk.

Thanks!
