### ISSUE TITLE
Found Error!

### ISSUE THREAD

**Issue by Gouryella** [ictnlp/PLUVR#7]
How can I find ‘bert_flickr_model.pth.tar’ file?

(pluvr) root@96811c496d05:/home/PLUVR/visual_grounding# python generate_bboxes.py 
/root/miniconda3/envs/pluvr/lib/python3.9/site-packages/torch/nn/_reduction.py:42: UserWarning: size_average and reduce args will be deprecated, please use reduction='mean' instead.
  warnings.warn(warning.format(ret))
Traceback (most recent call last):
  File "/home/PLUVR/visual_grounding/generate_bboxes.py", line 178, in <module>
    main()
  File "/home/PLUVR/visual_grounding/generate_bboxes.py", line 47, in main
    pretrained_dict = torch.load(pretrained_file)['state_dict']
  File "/root/miniconda3/envs/pluvr/lib/python3.9/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/miniconda3/envs/pluvr/lib/python3.9/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/miniconda3/envs/pluvr/lib/python3.9/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/PLUVR/visual_grounding/saved_models/bert_flickr_model.pth.tar'

**Comment by ZhenLEI96** [comment]
I just had this issue too.

Pretrained models can be found from the [link](https://drive.google.com/drive/folders/1-DXvhEbWQtVWAUT_-G19zlz-0Ekcj5d7).

This link can be found in [Visual Grounding](https://github.com/zyang-ur/onestage_grounding/tree/master/saved_models)

**Comment by Gouryella** [comment]
> I just had this issue too.
> 
> Pretrained models can be found from the [link](https://drive.google.com/drive/folders/1-DXvhEbWQtVWAUT_-G19zlz-0Ekcj5d7).
> 
> This link can be found in [Visual Grounding](https://github.com/zyang-ur/onestage_grounding/tree/master/saved_models)

Thank you very much. You have been very helpful to me.

**Comment by ZhenLEI96** [comment]
你好
&nbsp; &nbsp; &nbsp;请问你这份代码全部运行成功了吗？
&nbsp; &nbsp; &nbsp;我再运行vae的train.py代码时，报错找不到region_embedding.npy文件。
&nbsp; &nbsp; &nbsp;github上有同样的问题，但是目前没人进行解答。
&nbsp; &nbsp; &nbsp;请问我应该怎么做？











------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ictnlp/PLUVR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月7日(星期五) 下午3:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ictnlp/PLUVR] Found Error! (Issue #7)





  
I just had this issue too.
 
Pretrained models can be found from the link.
 
This link can be found in Visual Grounding
  
Thank you very much. You have been very helpful to me.

**Comment by Gouryella** [comment]
> 你好 &nbsp; &nbsp; &nbsp;请问你这份代码全部运行成功了吗？ &nbsp; &nbsp; &nbsp;我再运行vae的train.py代码时，报错找不到region_embedding.npy文件。 &nbsp; &nbsp; &nbsp;github上有同样的问题，但是目前没人进行解答。 &nbsp; &nbsp; &nbsp;请问我应该怎么做？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ictnlp/PLUVR" ***@***.***&gt;; 发送时间:&nbsp;2023年4月7日(星期五) 下午3:01 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [ictnlp/PLUVR] Found Error! (Issue #7) I just had this issue too. Pretrained models can be found from the link. This link can be found in Visual Grounding Thank you very much. You have been very helpful to me. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

I have successfully resolved it, and I think I can share the file with you.

**Comment by ZhenLEI96** [comment]
> 

Thank you. 
But I also successfully reproduced it. 
However, there is an average gap of 1.8 between my experimental results and the paper's results. 
What is your result? I would also like to ask about your environment configuration.

**Comment by Gouryella** [comment]
> 

I can't reproduce it, I encountered an error 
`'hydra.errors.ConfigCompositionException: Could not override 'common_eval.path'. To append to your config use +common_eval.path=null' during the last step 'fairseq-train'.`

**Comment by Gouryella** [comment]
> > 
> 
> Thank you. But I also successfully reproduced it. However, there is an average gap of 1.8 between my experimental results and the paper's results. What is your result? I would also like to ask about your environment configuration.


I can't reproduce it, I encountered an error
'hydra.errors.ConfigCompositionException: Could not override 'common_eval.path'. To append to your config use +common_eval.path=null' during the last step 'fairseq-train'.
